config-version: 2
message-mode: chat

enabled: true
ops-bypass: true

always-allowed:
  - shardedcore
  - score
  - shardedc

groups:
  default:
    commands:
      - help
      - list
      - msg
      - tell
      - whisper
      - w
      - reply
      - r
      - bal
      - balance
      - craft
      - fix
      - trash
      - chattoggle
      - togglechat
      - ct
      - nightvision
      - nv
      - backpack
      - bp
      - armortrims
      - trims
      - fly
      - autosmelt
      - rtp
      - wild
      - spawn
      - spawnselect
      - eglow
      - glows
      - chatcolor
      - namecolor
      - wardrobe
      - tags
      - tag
      - deathtoggle
      - jointoggle
      - mobtoggle
      - settings
      - killstreak
      - toolname
      - tokenshop
      - pets
      - pet
      - temprank
      - rankshop
      - guide
      - rules
      - team
      - teams
      - discord
      - store
      - pm
      - msgtoggle
      - ping
      - live
      - cf
      - coinflip
      - paytoggle
      - pay
      - tpa
      - tpahere
      - tpaccept
      - tpacancel
      - tpatoggle
      - tpauto

  ranks:
    permission: shardedcore.commandwhitelist.ranks
    commands:
      - duel
      - rewards
      - dailyrewards
      - weeklyrewards
      - crates
      - leaderboard
      - leaderboards
      - media
      - tempranks

  immortal:
    permission: shardedcore.commandwhitelist.immortal
    commands:
      - hide
      - spawners
      - graves
      - koth
      - outpost
      - combat
      - arena

  media:
    permission: shardedcore.commandwhitelist.media
    commands:
      - live
