export type CatalogEmoji = {
  id: string;
  char: string;
  name: string;
  category: string;
  keywords: string;
};

export const EMOJI_CATEGORIES = [
  'Weapons',
  'Tools',
  'Nature & Weather',
  'Status',
  'Symbols',
  'Decorative',
  'Music',
  'Navigation',
  'Magic',
  'Economy',
  'Hearts',
  'Custom',
] as const;

type Row = [string, string, string, string?];

const ROWS: Row[] = [
  ['🗡', 'Dagger', 'Weapons', 'sword blade weapon melee'],
  ['⚔', 'Crossed swords', 'Weapons', 'sword pvp combat'],
  ['🏹', 'Bow', 'Weapons', 'arrow ranged shoot'],
  ['🔱', 'Trident', 'Weapons', 'spear ocean'],
  ['🛡', 'Shield', 'Weapons', 'block defense'],
  ['⛨', 'Shield crest', 'Weapons', 'shield guard'],
  ['💣', 'Bomb', 'Weapons', 'tnt explode'],
  ['🔪', 'Knife', 'Weapons', 'blade dagger'],
  ['⛓', 'Chains', 'Weapons', 'bind chain'],
  ['🪓', 'Axe', 'Tools', 'chop wood weapon'],
  ['⛏', 'Pickaxe', 'Tools', 'mine pick tool'],
  ['🎣', 'Fishing rod', 'Tools', 'fish hook'],
  ['🔨', 'Hammer', 'Tools', 'build smith'],
  ['🔧', 'Wrench', 'Tools', 'spanner fix'],
  ['🔩', 'Bolt', 'Tools', 'nut screw'],
  ['⚙', 'Gear', 'Tools', 'settings cog redstone'],
  ['🛠', 'Hammer and wrench', 'Tools', 'repair build'],
  ['🪣', 'Bucket', 'Tools', 'water lava milk'],
  ['🧰', 'Toolbox', 'Tools', 'kit'],
  ['🔑', 'Key', 'Tools', 'lock unlock'],
  ['🔒', 'Locked', 'Tools', 'lock private'],
  ['🔓', 'Unlocked', 'Tools', 'lock open'],
  ['🧲', 'Magnet', 'Tools', 'attract'],
  ['🧪', 'Potion', 'Tools', 'brew alchemy flask'],
  ['✂', 'Shears', 'Tools', 'cut scissors wool'],
  ['🪝', 'Hook', 'Tools', 'fishing grapple'],
  ['🧹', 'Broom', 'Tools', 'sweep clean'],
  ['🔭', 'Spyglass', 'Tools', 'scope look'],
  ['🔥', 'Fire', 'Nature & Weather', 'flame burn'],
  ['🌊', 'Wave', 'Nature & Weather', 'water ocean sea'],
  ['☄', 'Comet', 'Nature & Weather', 'meteor star'],
  ['⚡', 'Lightning', 'Nature & Weather', 'bolt thunder storm'],
  ['☁', 'Cloud', 'Nature & Weather', 'sky weather'],
  ['☀', 'Sun', 'Nature & Weather', 'day light'],
  ['☂', 'Umbrella', 'Nature & Weather', 'rain'],
  ['☔', 'Rain', 'Nature & Weather', 'weather storm'],
  ['❄', 'Snowflake', 'Nature & Weather', 'snow ice cold'],
  ['❅', 'Snowflake outline', 'Nature & Weather', 'snow'],
  ['☃', 'Snowman', 'Nature & Weather', 'snow winter'],
  ['☽', 'Crescent moon', 'Nature & Weather', 'night'],
  ['☾', 'Moon', 'Nature & Weather', 'night'],
  ['🌑', 'New moon', 'Nature & Weather', 'night'],
  ['🌕', 'Full moon', 'Nature & Weather', 'night'],
  ['🌈', 'Rainbow', 'Nature & Weather', 'sky'],
  ['💧', 'Droplet', 'Nature & Weather', 'water'],
  ['🌬', 'Wind', 'Nature & Weather', 'blow air'],
  ['🌀', 'Cyclone', 'Nature & Weather', 'whirl wind'],
  ['🌋', 'Volcano', 'Nature & Weather', 'lava'],
  ['☘', 'Clover', 'Nature & Weather', 'luck nature'],
  ['🍀', 'Four-leaf clover', 'Nature & Weather', 'luck'],
  ['🌿', 'Herb', 'Nature & Weather', 'plant leaf'],
  ['🍃', 'Leaves', 'Nature & Weather', 'leaf wind'],
  ['🍂', 'Fallen leaf', 'Nature & Weather', 'autumn'],
  ['🍁', 'Maple leaf', 'Nature & Weather', 'autumn'],
  ['🌾', 'Wheat', 'Nature & Weather', 'crop farm'],
  ['🌲', 'Evergreen', 'Nature & Weather', 'tree spruce'],
  ['🌳', 'Tree', 'Nature & Weather', 'oak wood'],
  ['🌴', 'Palm', 'Nature & Weather', 'jungle'],
  ['🌵', 'Cactus', 'Nature & Weather', 'desert'],
  ['🌷', 'Tulip', 'Nature & Weather', 'flower'],
  ['🌼', 'Blossom', 'Nature & Weather', 'flower'],
  ['🌻', 'Sunflower', 'Nature & Weather', 'flower'],
  ['⚘', 'Flower', 'Nature & Weather', 'plant'],
  ['☠', 'Skull', 'Status', 'death danger poison'],
  ['💀', 'Skull face', 'Status', 'death'],
  ['⏳', 'Hourglass', 'Status', 'time wait cooldown'],
  ['⌛', 'Hourglass done', 'Status', 'time finished'],
  ['ℹ', 'Information', 'Status', 'info help'],
  ['✎', 'Pencil', 'Status', 'edit write set by'],
  ['✏', 'Pencil tip', 'Status', 'edit write'],
  ['✔', 'Heavy check', 'Status', 'yes ok done'],
  ['✓', 'Check', 'Status', 'yes ok'],
  ['✘', 'Ballot cross', 'Status', 'no x close fail'],
  ['✕', 'Multiply cross', 'Status', 'no x close'],
  ['✖', 'Heavy cross', 'Status', 'no x'],
  ['✅', 'Checked box', 'Status', 'yes complete'],
  ['❌', 'Cross mark', 'Status', 'no fail'],
  ['⛔', 'No entry', 'Status', 'stop deny'],
  ['🚫', 'Prohibited', 'Status', 'ban deny'],
  ['⚠', 'Warning', 'Status', 'alert caution'],
  ['❗', 'Exclamation', 'Status', 'alert important'],
  ['❕', 'White exclamation', 'Status', 'alert'],
  ['❓', 'Question', 'Status', 'help unknown'],
  ['❔', 'White question', 'Status', 'help'],
  ['‼', 'Double exclamation', 'Status', 'alert'],
  ['♨', 'Hot', 'Status', 'heat lava'],
  ['🔔', 'Bell', 'Status', 'notify alert'],
  ['🔕', 'Bell off', 'Status', 'mute silent'],
  ['📌', 'Pin', 'Status', 'mark'],
  ['📍', 'Round pin', 'Status', 'location mark'],
  ['👑', 'Crown', 'Status', 'king rank vip'],
  ['🏆', 'Trophy', 'Status', 'win reward rank'],
  ['🎯', 'Target', 'Status', 'goal aim'],
  ['💬', 'Speech', 'Status', 'chat message'],
  ['📢', 'Announcement', 'Status', 'broadcast'],
  ['📣', 'Megaphone', 'Status', 'shout'],
  ['👀', 'Eyes', 'Status', 'look spectate'],
  ['💤', 'Sleep', 'Status', 'afk zzz'],
  ['🔴', 'Red dot', 'Status', 'offline busy'],
  ['🟢', 'Green dot', 'Status', 'online'],
  ['🟡', 'Yellow dot', 'Status', 'away'],
  ['🔵', 'Blue dot', 'Status', 'info'],
  ['⚪', 'White dot', 'Status', 'empty'],
  ['⚫', 'Black dot', 'Status', 'offline'],
  ['★', 'Black star', 'Symbols', 'favorite rank'],
  ['☆', 'White star', 'Symbols', 'favorite rank'],
  ['✦', 'Four-point star', 'Symbols', 'sparkle'],
  ['✧', 'Sparkle star', 'Symbols', 'magic'],
  ['✪', 'Circled star', 'Symbols', 'rank badge'],
  ['✫', 'Open star', 'Symbols', 'rank'],
  ['✬', 'Black centre star', 'Symbols', 'rank'],
  ['✭', 'Outlined star', 'Symbols', 'rank'],
  ['✮', 'Heavy star', 'Symbols', 'rank'],
  ['✯', 'Pinwheel star', 'Symbols', 'rank'],
  ['✰', 'Shadowed star', 'Symbols', 'rank'],
  ['✶', 'Six-point star', 'Symbols', 'sparkle'],
  ['✷', 'Eight-point star', 'Symbols', 'sparkle'],
  ['❈', 'Heavy sparkle', 'Symbols', 'decorative'],
  ['❉', 'Balloon sparkle', 'Symbols', 'decorative'],
  ['❖', 'Diamond sparkle', 'Symbols', 'rare'],
  ['⚑', 'Black flag', 'Symbols', 'banner claim'],
  ['⚐', 'White flag', 'Symbols', 'banner'],
  ['♠', 'Spade', 'Symbols', 'card suit'],
  ['♣', 'Club', 'Symbols', 'card suit'],
  ['♥', 'Heart suit', 'Symbols', 'card'],
  ['♦', 'Diamond suit', 'Symbols', 'card'],
  ['♤', 'White spade', 'Symbols', 'card'],
  ['♧', 'White club', 'Symbols', 'card'],
  ['♢', 'White diamond', 'Symbols', 'card'],
  ['♔', 'White king', 'Symbols', 'chess'],
  ['♕', 'White queen', 'Symbols', 'chess'],
  ['♖', 'White rook', 'Symbols', 'chess'],
  ['♗', 'White bishop', 'Symbols', 'chess'],
  ['♘', 'White knight', 'Symbols', 'chess'],
  ['♙', 'White pawn', 'Symbols', 'chess'],
  ['♚', 'Black king', 'Symbols', 'chess'],
  ['♛', 'Black queen', 'Symbols', 'chess'],
  ['♜', 'Black rook', 'Symbols', 'chess'],
  ['♝', 'Black bishop', 'Symbols', 'chess'],
  ['♞', 'Black knight', 'Symbols', 'chess'],
  ['♟', 'Black pawn', 'Symbols', 'chess'],
  ['⚜', 'Fleur-de-lis', 'Symbols', 'royal'],
  ['⚛', 'Atom', 'Symbols', 'science'],
  ['☯', 'Yin yang', 'Symbols', 'balance'],
  ['☮', 'Peace', 'Symbols', 'peace'],
  ['⚕', 'Medical', 'Symbols', 'heal'],
  ['⚖', 'Scales', 'Symbols', 'balance justice'],
  ['⚗', 'Alembic', 'Symbols', 'alchemy potion'],
  ['∞', 'Infinity', 'Symbols', 'endless'],
  ['§', 'Section', 'Symbols', 'sign'],
  ['•', 'Bullet', 'Symbols', 'dot list'],
  ['·', 'Middle dot', 'Symbols', 'separator'],
  ['†', 'Dagger mark', 'Symbols', 'footnote'],
  ['‡', 'Double dagger', 'Symbols', 'footnote'],
  ['°', 'Degree', 'Symbols', 'temp'],
  ['±', 'Plus minus', 'Symbols', 'math'],
  ['×', 'Multiply', 'Symbols', 'math x'],
  ['÷', 'Divide', 'Symbols', 'math'],
  ['≈', 'Approximate', 'Symbols', 'math'],
  ['≠', 'Not equal', 'Symbols', 'math'],
  ['≤', 'Less or equal', 'Symbols', 'math'],
  ['≥', 'Greater or equal', 'Symbols', 'math'],
  ['™', 'Trademark', 'Symbols', 'brand'],
  ['№', 'Numero', 'Symbols', 'number'],
  ['●', 'Black circle', 'Decorative', 'dot separator'],
  ['○', 'White circle', 'Decorative', 'dot'],
  ['◉', 'Fisheye', 'Decorative', 'circle target'],
  ['◎', 'Bullseye', 'Decorative', 'target'],
  ['■', 'Black square', 'Decorative', 'block'],
  ['□', 'White square', 'Decorative', 'block'],
  ['▪', 'Small square', 'Decorative', 'block'],
  ['▫', 'Small white square', 'Decorative', 'block'],
  ['◆', 'Black diamond', 'Decorative', 'gem'],
  ['◇', 'White diamond', 'Decorative', 'gem'],
  ['▲', 'Up triangle', 'Decorative', 'arrow'],
  ['▼', 'Down triangle', 'Decorative', 'arrow'],
  ['▶', 'Play right', 'Decorative', 'arrow'],
  ['◀', 'Play left', 'Decorative', 'arrow'],
  ['▮', 'Vertical bar', 'Decorative', 'separator'],
  ['▯', 'White vertical bar', 'Decorative', 'separator'],
  ['╏', 'Double dash vertical', 'Decorative', 'separator line'],
  ['│', 'Light vertical', 'Decorative', 'separator line'],
  ['┃', 'Heavy vertical', 'Decorative', 'separator line'],
  ['┆', 'Dashed vertical', 'Decorative', 'separator'],
  ['┊', 'Dotted vertical', 'Decorative', 'separator'],
  ['❘', 'Light vertical bar', 'Decorative', 'separator'],
  ['❙', 'Medium vertical bar', 'Decorative', 'separator'],
  ['❚', 'Heavy vertical bar', 'Decorative', 'separator'],
  ['─', 'Light horizontal', 'Decorative', 'line rule'],
  ['━', 'Heavy horizontal', 'Decorative', 'line rule'],
  ['┄', 'Dashed horizontal', 'Decorative', 'line'],
  ['┅', 'Heavy dashed horizontal', 'Decorative', 'line'],
  ['═', 'Double horizontal', 'Decorative', 'line'],
  ['║', 'Double vertical', 'Decorative', 'line separator'],
  ['┌', 'Corner down-right', 'Decorative', 'box'],
  ['┐', 'Corner down-left', 'Decorative', 'box'],
  ['└', 'Corner up-right', 'Decorative', 'box'],
  ['┘', 'Corner up-left', 'Decorative', 'box'],
  ['├', 'Tee right', 'Decorative', 'box'],
  ['┤', 'Tee left', 'Decorative', 'box'],
  ['┬', 'Tee down', 'Decorative', 'box'],
  ['┴', 'Tee up', 'Decorative', 'box'],
  ['┼', 'Cross', 'Decorative', 'box'],
  ['╭', 'Round corner down-right', 'Decorative', 'box'],
  ['╮', 'Round corner down-left', 'Decorative', 'box'],
  ['╯', 'Round corner up-left', 'Decorative', 'box'],
  ['╰', 'Round corner up-right', 'Decorative', 'box'],
  ['░', 'Light shade', 'Decorative', 'block shade'],
  ['▒', 'Medium shade', 'Decorative', 'block shade'],
  ['▓', 'Dark shade', 'Decorative', 'block shade'],
  ['█', 'Full block', 'Decorative', 'block'],
  ['▀', 'Upper block', 'Decorative', 'block'],
  ['▄', 'Lower block', 'Decorative', 'block'],
  ['✿', 'Flower mark', 'Decorative', 'floral'],
  ['❀', 'White flower', 'Decorative', 'floral'],
  ['❁', 'Eight petal', 'Decorative', 'floral'],
  ['❃', 'Teardrop flower', 'Decorative', 'floral'],
  ['✽', 'Heavy asterisk', 'Decorative', 'sparkle'],
  ['※', 'Reference mark', 'Decorative', 'note'],
  ['⁂', 'Asterism', 'Decorative', 'star'],
  ['【', 'Black lenticular bracket', 'Decorative', 'title'],
  ['】', 'Black lenticular bracket right', 'Decorative', 'title'],
  ['「', 'Corner bracket', 'Decorative', 'title quote'],
  ['」', 'Corner bracket right', 'Decorative', 'title quote'],
  ['『', 'White corner bracket', 'Decorative', 'title'],
  ['』', 'White corner bracket right', 'Decorative', 'title'],
  ['♫', 'Beamed notes', 'Music', 'song note'],
  ['♪', 'Eighth note', 'Music', 'song'],
  ['♬', 'Beamed sixteenths', 'Music', 'song'],
  ['♭', 'Flat', 'Music', 'note'],
  ['♯', 'Sharp', 'Music', 'note'],
  ['🎵', 'Musical note', 'Music', 'song'],
  ['🎶', 'Musical notes', 'Music', 'song'],
  ['🎸', 'Guitar', 'Music', 'song'],
  ['🎺', 'Trumpet', 'Music', 'song'],
  ['🥁', 'Drum', 'Music', 'song'],
  ['🎤', 'Microphone', 'Music', 'voice'],
  ['🎧', 'Headphones', 'Music', 'audio'],
  ['⚓', 'Anchor', 'Navigation', 'port sea harbor'],
  ['🧭', 'Compass', 'Navigation', 'direction'],
  ['🚩', 'Triangular flag', 'Navigation', 'marker'],
  ['🏁', 'Chequered flag', 'Navigation', 'finish race'],
  ['➤', 'Arrowhead', 'Navigation', 'pointer right'],
  ['➔', 'Heavy arrow', 'Navigation', 'right'],
  ['➜', 'Round arrow', 'Navigation', 'right'],
  ['➡', 'Right arrow', 'Navigation', 'east'],
  ['⬅', 'Left arrow', 'Navigation', 'west'],
  ['⬆', 'Up arrow', 'Navigation', 'north'],
  ['⬇', 'Down arrow', 'Navigation', 'south'],
  ['→', 'Thin right', 'Navigation', 'arrow'],
  ['←', 'Thin left', 'Navigation', 'arrow'],
  ['↑', 'Thin up', 'Navigation', 'arrow'],
  ['↓', 'Thin down', 'Navigation', 'arrow'],
  ['↔', 'Left right', 'Navigation', 'arrow'],
  ['↕', 'Up down', 'Navigation', 'arrow'],
  ['↖', 'Up left', 'Navigation', 'arrow'],
  ['↗', 'Up right', 'Navigation', 'arrow'],
  ['↘', 'Down right', 'Navigation', 'arrow'],
  ['↙', 'Down left', 'Navigation', 'arrow'],
  ['↩', 'Hook left', 'Navigation', 'return back'],
  ['↪', 'Hook right', 'Navigation', 'forward'],
  ['⇄', 'Swap horizontal', 'Navigation', 'exchange'],
  ['⇅', 'Swap vertical', 'Navigation', 'exchange'],
  ['⤴', 'Arrow curving up', 'Navigation', 'up'],
  ['⤵', 'Arrow curving down', 'Navigation', 'down'],
  ['✨', 'Sparkles', 'Magic', 'enchant glow'],
  ['🔮', 'Crystal ball', 'Magic', 'fortune mage'],
  ['🌟', 'Glowing star', 'Magic', 'enchant'],
  ['💫', 'Dizzy star', 'Magic', 'enchant swirl'],
  ['⭐', 'Star', 'Magic', 'favorite'],
  ['🪄', 'Magic wand', 'Magic', 'spell'],
  ['🧿', 'Nazar', 'Magic', 'charm ward'],
  ['🕯', 'Candle', 'Magic', 'light ritual'],
  ['📜', 'Scroll', 'Magic', 'quest lore'],
  ['📖', 'Open book', 'Magic', 'enchant book'],
  ['📕', 'Red book', 'Magic', 'book'],
  ['📗', 'Green book', 'Magic', 'book'],
  ['📘', 'Blue book', 'Magic', 'book'],
  ['📚', 'Books', 'Magic', 'library'],
  ['🔯', 'Dotted star', 'Magic', 'seal'],
  ['💰', 'Money bag', 'Economy', 'coins reward price'],
  ['💎', 'Gem', 'Economy', 'diamond rare'],
  ['🪙', 'Coin', 'Economy', 'money gold'],
  ['💵', 'Banknote', 'Economy', 'money cash'],
  ['💳', 'Card', 'Economy', 'pay'],
  ['💸', 'Flying money', 'Economy', 'spend'],
  ['🏦', 'Bank', 'Economy', 'money'],
  ['🛒', 'Cart', 'Economy', 'shop buy'],
  ['📦', 'Package', 'Economy', 'crate box'],
  ['🎁', 'Gift', 'Economy', 'reward crate'],
  ['🏷', 'Price tag', 'Economy', 'shop label price'],
  ['🏪', 'Shop', 'Economy', 'store market'],
  ['❤', 'Red heart', 'Hearts', 'life health love'],
  ['♥', 'Black heart', 'Hearts', 'life health'],
  ['♡', 'White heart', 'Hearts', 'life'],
  ['❣', 'Heart exclamation', 'Hearts', 'life'],
  ['💖', 'Sparkling heart', 'Hearts', 'love'],
  ['💘', 'Heart arrow', 'Hearts', 'love'],
  ['💗', 'Growing heart', 'Hearts', 'love'],
  ['💓', 'Beating heart', 'Hearts', 'life'],
  ['💕', 'Two hearts', 'Hearts', 'love'],
  ['💞', 'Revolving hearts', 'Hearts', 'love'],
  ['💔', 'Broken heart', 'Hearts', 'death'],
  ['🖤', 'Black heart emoji', 'Hearts', 'life'],
  ['🤍', 'White heart emoji', 'Hearts', 'life'],
  ['💚', 'Green heart', 'Hearts', 'life health'],
  ['💙', 'Blue heart', 'Hearts', 'life'],
  ['💛', 'Yellow heart', 'Hearts', 'life'],
  ['💜', 'Purple heart', 'Hearts', 'life'],
];

function codepointId(char: string): string {
  return Array.from(char)
    .map((part) => (part.codePointAt(0) ?? 0).toString(16))
    .join('-');
}

export const EMOJI_CATALOG: CatalogEmoji[] = ROWS.map(([char, name, category, keywords]) => ({
  id: `${category}-${codepointId(char)}`,
  char,
  name,
  category,
  keywords: keywords ?? '',
}));

export const REQUIRED_EMOJI = [
  '🗡',
  '🔥',
  '⛏',
  '🪓',
  '⏳',
  '🌊',
  '✘',
  '☄',
  '☠',
  '⛨',
  '★',
  '☆',
  '🎣',
  '⚓',
  '⚡',
  '☁',
  '♫',
  '●',
  '╏',
  '⚑',
  '☀',
  'ℹ',
  '✎',
];

export function filterEmojis<T extends { char: string; name: string; category: string; keywords?: string }>(
  entries: T[],
  query: string,
  category: string,
): T[] {
  const needle = query.trim().toLowerCase();
  return entries.filter((entry) => {
    if (category !== 'All' && entry.category !== category) return false;
    if (!needle) return true;
    return (
      entry.char.includes(query.trim()) ||
      entry.name.toLowerCase().includes(needle) ||
      entry.category.toLowerCase().includes(needle) ||
      (entry.keywords ?? '').toLowerCase().includes(needle)
    );
  });
}
