# Portal RTP - touch nether portal in portal-world to open gui.yml
portal-world: "factions"
target-world: "world"
border-label: "5K x 5K"
gui-cooldown-ms: 2000

center-x: 0
center-z: 0
min-radius: 100
max-radius: 5000
max-attempts: 25
cooldown-seconds: 30
