config-version: 1
message-mode: chat

# Show your own nametag in third-person (F5) when false.
hide-own: false
height: 2.35
line-gap: 0.28
scale: 1.0
shadow: true
see-through: false
background: false
update-interval-ticks: 5

lines:
  - '%luckperms_prefix%%player_name%'
  - '&7%shardedcore_balance_formatted% &8| &f%shardedcore_team%'
