config-version: 2
message-mode: chat
cooldown-hours: 168
picker-title: '&8Weekly Rewards'
picker-size: 27

sounds:
  win: ENTITY_PLAYER_LEVELUP

rewards:
  tokens_small:
    display: '500 Tokens'
    rarity-label: 'Common'
    rarity-color: '&7'
    material: SUNFLOWER
    slot: 11
    commands:
      - 'tokens give %player% 500'
  tokens_medium:
    display: '1500 Tokens'
    rarity-label: 'Uncommon'
    rarity-color: '&a'
    material: GOLD_INGOT
    slot: 12
    commands:
      - 'tokens give %player% 1500'
  tokens_large:
    display: '3000 Tokens'
    rarity-label: 'Rare'
    rarity-color: '&b'
    material: DIAMOND
    slot: 13
    commands:
      - 'tokens give %player% 3000'
  shard_key:
    display: '3 Shard Keys'
    rarity-label: 'Epic'
    rarity-color: '&d'
    material: PURPLE_CANDLE
    slot: 14
    commands:
      - 'crate key give %player% shard 3'
  craft_week:
    display: '/craft for 7 days'
    rarity-label: 'Legendary'
    rarity-color: '&6'
    material: CRAFTING_TABLE
    slot: 15
    commands:
      - 'lp user %player% permission settemp sharded.craft.use true 7d'
