config-version: 2
message-mode: chat
enabled: true
bypass-permission: shardedcore.command.bypass
unknown-message: '&#4498DB&lCOMMANDS &8▷ &fYou do not have Permission.'
sound:
  enabled: true
  sound: block.note_block.bass
  volume: 0.8
  pitch: 0.8
commands:
- help
- spawn
- setspawn
- rtp
- wild
- rtpqueue
- rtpq
- discord
- store
- webstore
- apply
- media
- settings
- setting
- ping
- kit
- kits
- k
- shop
- rules
- w
- msg
- tell
- whisper
- m
- message
- r
- reply
- bal
- balance
- money
- pay
- baltop
- home
- homes
- sethome
- delhome
- trash
- craft
- wb
- workbench
- anvil
- toolsmith
- smithing
- cf
- coinflip
- ranks
- crates
- crate
- scrates
- itemshop
- dailyitemshop
- rotatingshop
- crate
- tokenshop
- tokenmethods
- namegradients
- namegradient
- namecolor
- namecolours
- duel
- duels
- queue
- elo
- elotop
- eglow
- outpost
- sell
- worth
- live
- guide
- stats
- leaderboard
- rules
- killrewards
- krewards
- playtimerewards
- ptrewards
- playtime
- chattoggle
- msgtoggle
- livetoggle
- nvtoggle
- nv
- joinleavetoggle
- jointoggle
- deathtoggle
- nightvisiontoggle
- nightvision
- nv
- tabbossbar
- tabscoreboard
- giveaway
- gws
- gw
- giveaways
- vault
- vaults
- pv
- pvadmin
- leave
- chatcolor
- chatcolour
- cc
- chatcolorgradient
- tag
- chattag
- tags
- ec
- enderchest
- echest
- fly
- shardedtool
- stool
- crystal
- crystals
- crystalshop
- team
- teams
- glows
- glow
- wipe
- tags
- website
- survival
- events
- diasmp
- dev
- patron
- promote
- demote
- tools
- rtpqueuetoggle
- staffgoto
- moneymethods
- cosmetics
- cosmetic
- wardrobe
- hatshop
- hatcosmetics
- pets
- pet
- temprank
- rankshop
- temprankshop
- glows
- glowing
- graves
- itemedit
- ie
- serveritem
- si
- itemstorage
- is
- lb
- lbsetline
- setline
- lbremove
- lbplace
- lbpurge
- lbclean
always-allowed:
- shardedcore
- score
- shardedc
