config-version: 2
message-mode: chat

# Minimum time between spam warning messages (prevents chat flood)
warn-cooldown-ms: 2500

anti-swear:
  enabled: true

swear-words:
  - badword1
  - badword2

anti-spam:
  enabled: true
  cooldown-ms: 1500
  repeat-limit: 3

anti-spam-commands:
  enabled: true
  cooldown-ms: 3000
  commands:
    - msg
    - tell
    - w
    - r
    - reply
