config-version: 2
message-mode: chat
cooldown-hours: 24
picker-title: '&8Daily Rewards'
picker-size: 27

sounds:
  win: ENTITY_PLAYER_LEVELUP

rewards:
  tokens_small:
    display: '100 Tokens'
    rarity-label: 'Common'
    rarity-color: '&7'
    material: SUNFLOWER
    slot: 11
    commands:
      - 'tokens give %player% 100'
  tokens_medium:
    display: '250 Tokens'
    rarity-label: 'Uncommon'
    rarity-color: '&a'
    material: GOLD_INGOT
    slot: 12
    commands:
      - 'tokens give %player% 250'
  tokens_large:
    display: '500 Tokens'
    rarity-label: 'Rare'
    rarity-color: '&b'
    material: DIAMOND
    slot: 13
    commands:
      - 'tokens give %player% 500'
  shard_key:
    display: '1 Shard Key'
    rarity-label: 'Epic'
    rarity-color: '&d'
    material: PURPLE_CANDLE
    slot: 14
    commands:
      - 'crate key give %player% shard 1'
  craft_day:
    display: '/craft for 1 day'
    rarity-label: 'Legendary'
    rarity-color: '&6'
    material: CRAFTING_TABLE
    slot: 15
    commands:
      - 'lp user %player% permission settemp sharded.craft.use true 1d'
