config-schema: "10802"

motd:
  lines:
    - "&#AD4EFF&lSHARDEDMC &8▷ &7[1.21+]"
    - "&#FFE300⚓ &#FFE300&lSEASON 1 SOON &#FFE300⚓"
  center-width: 48

server-icon:
  enabled: false
  image: "default-server-icon.png"

hover:
  enabled: false
  messages:
    - ""
    - "&#AD4EFF&lSHARDEDMC &#AD4EFF&lNetwork &8| &7[1.21+]"
    - ""
    - "&#AD4EFFɪɴꜰᴏʀᴍᴀᴛɪᴏɴ:"
    - "&#FF005D⚓ &fDiscord &8▷ &#FF005Dᴅɪsᴄᴏʀᴅ.ɢɢ/shardedmc"
    - "&#9FFF00⛨ &fStore &8▷ &#9FFF00ᴄᴏᴍɪɴɢ sᴏᴏɴ"
    - ""
    - "&#AD4EFF☀ &fPlay with &#AD4EFF&n{online_players}&f other players"

maintenance-motd:
  kick-message:
    - ""
    - "&#FF0000&lMAINTENANCE"
    - "&fThis Server is currently in Maintenance"
    - ""
    - "&fPlease Be patient, Join the discord for more updates:"
    - "&#FFD900▷ &#FFD900&ndiscord.gg/shardedmc&f &#FFD900◁"
  protocol-text: true
  text: "Maintenance"
  protocol-version: -1
