config-schema: "10802"

motd:
  lines:
    - "&#AD4EFF&lSHARDEDMC &8▷ &7[1.21+]"
    - "&#FFE300⚓ &#FFE300&lSEASON 1 SOON &#FFE300⚓"
  center-width: 48

server-icon:
  enabled: false
  image: "default-server-icon.png"

hover:
  enabled: true
  messages:
    - "&d&lSHARDEDMC NETWORK &8| &7 1.21.11"
    - ""
    - "&#A183CD🔥 ɪɴꜰᴏʀᴍᴀᴛɪᴏɴ:"
    - "&7▶ &fDiscord: &dᴅɪsᴄᴏʀᴅ.ɢɢ/shardedmc"
    - "&7▶ &fStore: &dᴄᴏᴍɪɴɢ sᴏᴏɴ"
    - "&fplay with {online_players} other players"

maintenance-motd:
  kick-message:
    - ""
    - "&#FF0000&lMaintenance"
    - "&fThis server is currently in downtime"
    - ""
    - "&fIf you believe there is an error contact staff via"
    - "&#FFD900▷ &n&ldiscord.gg/shardedmc&f &#FFD900◁"
  protocol-text: true
  text: "Maintenance"
  protocol-version: -1
