# ShardedVelocityCore Configuration

status-refresh-seconds = 1
status-sync-interval-seconds = 1
whitelist-as-maintenance = true
lobby-server = "lobby"

tracked-servers = ["survival", "events", "diasmp"]
queue-servers = ["lobby", "survival", "events", "diasmp"]

maintenance-servers = []

[queue]
  action-bar = "&#4498DB#%numberinqueue% in queue to &n%server_color%%server%&r &7(Wating: %numberofpeoplewaitinginqueue%)"
  prefix = "&#4498DB&lQUEUE &8▷&r "
  default-server = "survival"
  action-bar-interval-ticks = 10

  [queue.colors]
    position = "&#FFFFFF"
    server = "&#8AFF00"
    waiting = "&#AAAAAA"
    success = "&#8AFF00"
    error = "&#FF0000"
    accent = "&#4498DB"

  [queue.server-colors]
    lobby = "&#4498DB"
    survival = "&#8AFF00"
    events = "&#FFAA00"
    diasmp = "&#4498DB"

  [queue.max-players]
    lobby = 500
    survival = 100
    events = 200
    diasmp = 150
