#Minecraft server properties
#ShardedMC Server Properties
motd=A ShardedMC High-Performance Server
server-port=25565
max-players=100
online-mode=true
level-name=world
level-seed=
level-type=minecraft\:normal
view-distance=10
simulation-distance=10
hardcore=false
pvp=true
spawn-protection=16
max-tick-time=60000
max-world-size=29999984
gamemode=survival
force-gamemode=false
allow-nether=true
enable-command-block=false
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
white-list=false
enforce-whitelist=false
player-idle-timeout=0
resource-pack=
use-native-transport=true
enable-jmx-monitoring=false
enable-status=true
hide-online-players=false
entity-broadcast-range-percentage=100
text-filtering-config=
op-permission-level=4
function-permission-level=2
rate-limit=0
sync-chunk-writes=true
enable-query=false
query.port=25565
prevent-proxy-connections=false
log-ips=true
