# When XP orbs clump past this amount they turn into bottles.
convert-merges: true
convert-spawns: true
experience-per-bottle: 7
min-bottles: 2
min-experience: 14
max-bottles: 64
keep-leftover-orb: true
