# The spawner shop. Its icon and its slot in the main menu sit in ../config.yml

menu:
  title: "Spawners"
  rows: 3
  pages: 1

buttons:

  previous:
    slot: 21
    material: LIME_DYE
    name: "&#94FF00&lPREVIOUS PAGE"
    lore:
      - "&8Description"
      - ""
      - "&#94FF00&lINFORMATION:"
      - "&#94FF00| &f&lGO ONE PAGE BACK"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO NAVIGATE"

  return:
    slot: 22
    material: FLOWER_BANNER_PATTERN
    name: "&#FF0000&lBACK"
    lore:
      - "&8Description"
      - ""
      - "&#FF0000&lINFORMATION:"
      - "&#FF0000| &f&lGO BACK TO THE"
      - "&#FF0000| &f&lSHOP MENU"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO RETURN"

  next:
    slot: 23
    material: LIME_DYE
    name: "&#94FF00&lNEXT PAGE"
    lore:
      - "&8Description"
      - ""
      - "&#94FF00&lINFORMATION:"
      - "&#94FF00| &f&lGO ONE PAGE FORWARD"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO NAVIGATE"

items:
  pig:
    page: 1
    slot: 10
    name: "&#FFB6C1&lPIG SPAWNER"
    material: SPAWNER
    price: 800
    command: "spawner give spawner %player% pig"
    lore:
      - "&8Description"
      - ""
      - "&#FFB6C1&lINFORMATION:"
      - "&#FFB6C1| &f&lGIVES A PIG SPAWNER"
      - ""
      - "&#FFB6C1⚓ &f&lPRICE: &#FFB6C1$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
  cow:
    page: 1
    slot: 11
    name: "&#C4A484&lCOW SPAWNER"
    material: SPAWNER
    price: 900
    command: "spawner give spawner %player% cow"
    lore:
      - "&8Description"
      - ""
      - "&#C4A484&lINFORMATION:"
      - "&#C4A484| &f&lGIVES A COW SPAWNER"
      - ""
      - "&#C4A484⚓ &f&lPRICE: &#C4A484$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
  zombie:
    page: 1
    slot: 12
    name: "&#80EE0B&lZOMBIE SPAWNER"
    material: SPAWNER
    price: 1000
    command: "spawner give spawner %player% zombie"
    lore:
      - "&8Description"
      - ""
      - "&#80EE0B&lINFORMATION:"
      - "&#80EE0B| &f&lGIVES A ZOMBIE SPAWNER"
      - ""
      - "&#80EE0B⚓ &f&lPRICE: &#80EE0B$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
  skeleton:
    page: 1
    slot: 13
    name: "&#E3E3E3&lSKELETON SPAWNER"
    material: SPAWNER
    price: 1200
    command: "spawner give spawner %player% skeleton"
    lore:
      - "&8Description"
      - ""
      - "&#E3E3E3&lINFORMATION:"
      - "&#E3E3E3| &f&lGIVES A SKELETON SPAWNER"
      - ""
      - "&#E3E3E3⚓ &f&lPRICE: &#E3E3E3$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
  creeper:
    page: 1
    slot: 14
    name: "&#007E20&lCREEPER SPAWNER"
    material: SPAWNER
    price: 1400
    command: "spawner give spawner %player% creeper"
    lore:
      - "&8Description"
      - ""
      - "&#007E20&lINFORMATION:"
      - "&#007E20| &f&lGIVES A CREEPER SPAWNER"
      - ""
      - "&#007E20⚓ &f&lPRICE: &#007E20$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
  irongolem:
    page: 1
    slot: 15
    name: "&7&lIRON GOLEM SPAWNER"
    material: SPAWNER
    price: 2500
    command: "spawner give spawner %player% iron_golem"
    lore:
      - "&8Description"
      - ""
      - "&7&lINFORMATION:"
      - "&7| &f&lGIVES AN IRON GOLEM SPAWNER"
      - ""
      - "&7⚓ &f&lPRICE: &7$%price%"
      - ""
      - "&x&F&F&B&A&0&0▷&x&F&F&B&A&0&0&l&nCLICK TO BUY"
