Apply:
  message:
    - ""
    - "&#D66BFC✎ &lSTAFF APPLICATIONS&r &#D66BFC✎"
    - "&7[ɪɴғᴏʀᴍᴀᴛɪᴏɴ]"
    - ""
    - "&#D66BFC¦ &fWant to join the &#D66BFCstaff team&f?"
    - "&#D66BFC¦ &fApply on our &#D66BFCDiscord &fserver!"
    - ""
    - "&#D66BFC▷ &fLink: &#D66BFC&ndiscord.gg/shardedmc"
  url: "https://discord.gg/shardedmc"
  sound: "block.note_block.pling"

Discord:
  message:
    - ""
    - "&#00BDF9✉ &lDISCORD SERVER&r &#00BDF9✉"
    - "&7[ɪɴғᴏʀᴍᴀᴛɪᴏɴ]"
    - ""
    - "&#00BDF9¦ &fEverything happens on our &#00BDF9Discord&f,"
    - "&#00BDF9¦ &ffrom &#00BDF9giveaways &fto &#00BDF9season news&f!"
    - ""
    - "&#00BDF9▷ &fLink: &#00BDF9&ndiscord.gg/shardedmc"
  url: "https://discord.gg/shardedmc"
  sound: "block.note_block.pling"

Store:
  message:
    - ""
    - "&#97F900&l$ SERVER WEBSTORE $"
    - "&7[ɪɴғᴏʀᴍᴀᴛɪᴏɴ]"
    - ""
    - "&#97F900¦ &fKeep the server alive and grab"
    - "&#97F900¦ &#97F900ranks&f, &#97F900crystals &fand &#97F900keys &fin return!"
    - ""
    - "&#97F900▷ &fLink: &#97F900&nstore.shardedmc.net"
  url: "https://store.shardedmc.net"
  sound: "block.note_block.pling"

Media:
  message:
    - ""
    - "&#FF256E☀ &lMEDIA RANK&r &#FF256E☀"
    - "&7[ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ]"
    - ""
    - "&#FF256E¦ &fApply for the &#FF256EMedia Rank"
    - "&#FF256E¦ &finside our &#FF256EDiscord Server&f!"
    - ""
    - "&#FF256E▷ &fLink: &#FF256E&ndiscord.gg/shardedmc"
  url: "https://discord.gg/shardedmc"
  sound: "block.note_block.pling"

media:
  menu:
    enabled: true
    menu_title: "Media Requirements"
    size: 27
    open_permission: shardedcore.command.media
    items:
      filler:
        material: BLACK_STAINED_GLASS_PANE
        display_name: " "
        slots: [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
      twitch:
        material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjI1ODA0ODliMmQ0NGU1ZDlhOWIzZjgzNmVmMjE5ZjAzMTI5OTJkNDBiMTRkOTlmNTZjNWFmMDVjNDBmNzE1In19fQ==
        slot: 4
        name: "&#9146FF&lTWITCH"
        lore:
          - "&8Descriptions"
          - ""
          - "&#9146FF&lREQUIREMENTS"
          - "&#9146FF● &f10 Average &7(ʟɪᴠᴇ)"
          - "&#9146FF● &f1 Hour Stream &7(ʟɪᴠᴇ)"
          - "&#9146FF● &f50 Followers &7(ʟɪᴠᴇ)"
          - ""
          - "&#9146FF&lREWARDS"
          - "&#9146FF● &#FB08B9&lMEDIA &fRank"
          - "&#9146FF● &fAccess to (/live) command"
          - ""
          - "&#9146FF⚓ &fIP must be &#9146FFvisible"
          - ""
          - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To Apply"
        left_click_commands:
          - "[player] discord"
      youtube:
        material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDQ1NTg2MDY1ZjAyZTg1NTMwMTI1ZjQ2NmRmMTA3YzFjOGQzZTE0MzEwMTAzMmMyYjQ3ODA3MTE1YmJkYTJmMCJ9fX0=
        slot: 12
        name: "&#FF0000&lYOUTUBE"
        lore:
          - "&8Descriptions"
          - ""
          - "&#FF0000&lREQUIREMENTS"
          - "&#FF0000● &f500 Views &7(ᴠɪᴅᴇᴏ)"
          - "&#FF0000● &f50 Likes &7(ᴠɪᴅᴇᴏ)"
          - "&#FF0000● &f10 Average &7(ʟɪᴠᴇ)"
          - "&#FF0000● &f1 Hour Stream &7(ʟɪᴠᴇ)"
          - "&#FF0000● &f100 followers &7(ʟɪᴠᴇ)"
          - ""
          - "&#FF0000&lREWARDS"
          - "&#FF0000● &#FB08B9&lMEDIA &fRank"
          - "&#FF0000● &fAccess to (/live) command"
          - ""
          - "&#FF0000⚓ &fIP must be &#FF0000visible"
          - ""
          - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To Apply"
        left_click_commands:
          - "[player] discord"
      tiktok:
        material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNThkMDI5ODRhNDNlNmM2OTEwZDBkOTA4YTU3ZTA0MWMzY2ZiMWRkODgxYjViNzIwYzU1NTYzZTY4MWY1OWUwZSJ9fX0=
        slot: 14
        name: "&#E43A96&lTIKTOK"
        lore:
          - "&8Descriptions"
          - ""
          - "&#E43A96&lREQUIREMENTS"
          - "&#E43A96● &f1500 Views &7(ᴠɪᴅᴇᴏ)"
          - "&#E43A96● &f75 Likes &7(ᴠɪᴅᴇᴏ)"
          - "&#E43A96● &f10 Average &7(ʟɪᴠᴇ)"
          - "&#E43A96● &f1 Hour Stream &7(ʟɪᴠᴇ)"
          - "&#E43A96● &f100 Followers &7(ʟɪᴠᴇ)"
          - ""
          - "&#E43A96&lREWARDS"
          - "&#E43A96● &#FB08B9&lMEDIA &fRank"
          - "&#E43A96● &fAccess to (/live) command"
          - ""
          - "&#E43A96⚓ &fIP must be &#E43A96visible"
          - ""
          - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To Apply"
        left_click_commands:
          - "[player] discord"

whitelist:
  enabled: true
  bypass-permission: shardedcore.command.bypass
  unknown: "&#4498DB&lCOMMANDS &8▷ &fYou do not have Permission."
  proxy-commands:
    - server
    - hub
    - lobby
    - queue
  sound:
    enabled: true
    sound: "block.note_block.bass"
    volume: 0.8
    pitch: 0.8
  commands:
    - help
    - spawn
    - setspawn
    - rtp
    - wild
    - rtpqueue
    - rtpq
    - tpa
    - tpahere
    - tpaccept
    - tpyes
    - tpacancel
    - tpdeny
    - discord
    - store
    - webstore
    - apply
    - media
    - settings
    - setting
    - ping
    - kit
    - kits
    - shop
    - rules
    - w
    - msg
    - tell
    - whisper
    - m
    - message
    - r
    - reply
    - bal
    - balance
    - money
    - pay
    - baltop
    - home
    - homes
    - sethome
    - delhome
    - trash
    - craft
    - wb
    - workbench
    - anvil
    - toolsmith
    - smithing
    - cf
    - coinflip
    - crate
    - crates
    - sell
    - worth
    - live
    - guide
    - killrewards
    - krewards
    - playtimerewards
    - ptrewards
    - playtime
    - chattoggle
    - msgtoggle
    - livetoggle
    - tpatoggle
    - tpauto
    - nvtoggle
    - nv
    - crystaltoggle
    - fastcrystal
    - tpaheretoggle
    - joinleavetoggle
    - jointoggle
    - mobspawning
    - mobtoggle
    - deathtoggle
    - paytoggle
    - nightvisiontoggle
    - nightvision
    - nv
    - tabbossbar
    - tabscoreboard
    - giveaway
    - gws
    - gw
    - giveaways
    - vault
    - vaults
    - pv
    - pvadmin
    - leave
    - chatcolor
    - chatcolour
    - cc
    - chatcolorgradient
    - tag
    - chattag
    - tags
    - ec
    - enderchest
    - echest
    - fly
    - shardedtool
    - stool
    - crystal
    - crystals
    - crystalshop
    - team
    - teams
    - glows
    - glow
    - wipe
    - tags
    - website
    - survival
    - events
    - event
    - diasmp
    - server
    - dev
    - patron
    - promote
    - demote
    - tools
    - rtpqueuetoggle
    - staffgoto
    - moneymethods
    - cosmetics
    - cosmetic

servers:
  channel: BungeeCord
  usage: "&#00A2FF&lCORE &8▷ &fUse /server <name>"
  survival: survival
  events: events
  diasmp: diasmp
  dev: dev
  dev1: dev1
  dev2: dev2

scheduled:
  enabled: true
  interval-minutes: 15
  command: "asyncarenas reset warzone"

patron:
  title: "🔥 Patron"
  rows: 4
  open-sound: item.book.page_turn
  close-sound: block.barrel.close
  filler:
    material: GRAY_STAINED_GLASS_PANE
  close:
    slot: 31
    material: FLOWER_BANNER_PATTERN
    name: "&#FF0000&lCLOSE"
    lore:
      - "&8Description"
      - ""
      - "&#FF0000Information:"
      - "&#FF0000| &fClose this GUI by Clicking"
      - ""
      - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To Close"
  tier-1:
    slot: 11
    material: PINK_HARNESS
    command: store
    name: "&x&F&9&7&E&9&C&lP&x&F&9&9&7&A&F&lA&x&F&9&A&F&C&1&lT&x&F&9&C&8&D&4&lR&x&F&9&E&0&E&6&lO&x&F&9&F&9&F&9&lN &8[&fTier I&8]"
    lore:
      - "&8Description"
      - ""
      - "&x&F&9&7&E&9&CInformation:"
      - "&x&F&9&7&E&9&C| &fSpecial &x&F&9&7&E&9&CPatron &fRole on discord"
      - "&x&F&9&7&E&9&C| &fCustom &x&F&9&7&E&9&CPatron &fPrefix Ingame"
      - "&x&F&9&7&E&9&C| &fCustom Join Message"
      - "&x&F&9&7&E&9&C| &fName in &x&F&9&7&E&9&C# Patrons &fOn discord"
      - ""
      - "&x&F&9&7&E&9&CExtras:"
      - "&x&F&9&7&E&9&C| &f1M Ingame"
      - "&x&F&9&7&E&9&C| &f1K Crystals"
      - ""
      - "&x&F&9&7&E&9&CRequirements:"
      - "&x&F&9&7&E&9&C| &fMust Spend &x&F&9&7&E&9&C$50 On the Server"
      - "&x&F&9&7&E&9&C| &fYou have spent &x&F&9&7&E&9&C%spent%"
      - ""
      - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To View"
  tier-2:
    slot: 13
    material: LIGHT_BLUE_HARNESS
    command: store
    name: "&x&0&0&8&3&F&F&lP&x&1&8&9&5&F&F&lA&x&3&0&A&6&F&F&lT&x&4&8&B&8&F&F&lR&x&5&F&C&A&F&F&lO&x&7&7&D&B&F&F&lN&x&8&F&E&D&F&F+ &8[&x&8&F&E&D&F&FTier II&8]"
    lore:
      - "&8Description"
      - ""
      - "&x&8&F&E&D&F&FInformation:"
      - "&x&8&F&E&D&F&F| &fSpecial &x&8&F&E&D&F&FPatron+ &fRole on Discord"
      - "&x&8&F&E&D&F&F| &fCustom &x&8&F&E&D&F&FPatron &fPrefix Ingame"
      - "&x&8&F&E&D&F&F| &fCustom Join Message"
      - "&x&8&F&E&D&F&F| &fName in &x&8&F&E&D&F&F# Patrons &fon Discord"
      - "&x&8&F&E&D&F&F| &fAccess to &x&8&F&E&D&F&F/fly &fin Spawn"
      - "&x&8&F&E&D&F&F| &fCreate your Custom Crate &x&8&F&E&D&F&F[1 Week]"
      - ""
      - "&x&8&F&E&D&F&FExtras:"
      - "&x&8&F&E&D&F&F| &f2M Ingame Money"
      - "&x&8&F&E&D&F&F| &f2.8K Crystals"
      - ""
      - "&x&8&F&E&D&F&FRequirements:"
      - "&x&8&F&E&D&F&F| &fMust Spend &x&8&F&E&D&F&F$150 &fon the Server"
      - "&x&8&F&E&D&F&F| &fYou have spent &x&8&F&E&D&F&F%spent%"
      - ""
      - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To View"
  tier-3:
    slot: 15
    material: RED_HARNESS
    command: store
    name: "&x&F&F&0&0&0&0&lP&x&F&D&1&4&0&E&lA&x&F&A&2&7&1&C&lT&x&F&8&3&B&2&A&lR&x&F&5&4&F&3&9&lO&x&F&3&6&3&4&7&lN&x&F&0&7&6&5&5+&x&E&E&8&A&6&3+ &8[&x&E&E&8&A&6&3Tier III&8]"
    lore:
      - "&8Description"
      - ""
      - "&x&E&E&8&A&6&3Information:"
      - "&x&E&E&8&A&6&3| &fSpecial &x&E&E&8&A&6&3Patron++ &fRole on Discord"
      - "&x&E&E&8&A&6&3| &fCustom &x&E&E&8&A&6&3Patron &fPrefix Ingame"
      - "&x&E&E&8&A&6&3| &fCustom Join Message"
      - "&x&E&E&8&A&6&3| &fName in &x&E&E&8&A&6&3# Patrons &fon Discord"
      - "&x&E&E&8&A&6&3| &fAccess to &x&E&E&8&A&6&3/fly &fin Spawn"
      - "&x&E&E&8&A&6&3| &fCreate your Custom Crate &x&E&E&8&A&6&3[1 Week]"
      - "&x&E&E&8&A&6&3| &fAccess to &x&E&E&8&A&6&3/trims"
      - "&x&E&E&8&A&6&3| &fAccess to the &x&E&E&8&A&6&3Rainbow &fGlow"
      - "&x&E&E&8&A&6&3| &fAccess to all &x&E&E&8&A&6&3Cosmetics"
      - ""
      - "&x&E&E&8&A&6&3Extras:"
      - "&x&E&E&8&A&6&3| &f3M Ingame Money"
      - "&x&E&E&8&A&6&3| &f5K Crystals"
      - ""
      - "&x&E&E&8&A&6&3Requirements:"
      - "&x&E&E&8&A&6&3| &fMust Spend &x&E&E&8&A&6&3$250 &fon the Server"
      - "&x&E&E&8&A&6&3| &fYou have spent &x&E&E&8&A&6&3%spent%"
      - ""
      - "&x&F&F&B&A&0&0▷ &x&F&F&B&A&0&0&l&nCLICK&r &x&F&F&B&A&0&0To View"


