config-version: 1
message-mode: chat

cooldown-seconds: 600

platforms:
  - twitch.tv
  - youtube.com
  - youtu.be
  - kick.com
  - tiktok.com
  - discord.gg
  - discord.com

broadcast:
  - '&#FF0000&lLIVE &8▷ &f%player% &7is now streaming!'
  - '&#9FFF00&l[CLICK HERE TO WATCH] &8(&f%link%&8)'
