default-rows: 3
allow-in-combat: false
title: "&8Ender Chest"

messages:
  players-only: "&#FF0000&lERROR &8▷ &fOnly a player can use that."
  in-combat: "&#FF0000&lERROR &8▷ &fYou cannot open your ender chest in combat."
  no-permission: "&#FF0000&lERROR &8▷ &fYou do not have permission."
